// Generado por scripts/generar-ejemplo.ts. No editar a mano.
//
// Bitácora de una panadería ficticia del Valle de Aburrá, para poder mostrar
// el tablero de conclusiones sin datos de una empresa real.

import type { Fila, ValorCampo } from "@/lib/talleres/tipos";

export const EJEMPLO: { respuestas: Record<string, ValorCampo>; filas: Fila[] } = {
  "respuestas": {
    "tend.esp.valoracion": "na",
    "tend.sin.valoracion": "fav",
    "tend.pso.valoracion": "des",
    "tend.gob.valoracion": "des",
    "tend.sos.valoracion": "fav",
    "tend.cli.valoracion": "des",
    "tend.dig.valoracion": "fav",
    "tend.hip.valoracion": "fav",
    "tend.red.valoracion": "med",
    "tend.dem.valoracion": "des",
    "tend.ssa.valoracion": "med",
    "tend.urb.valoracion": "des",
    "tend.aut.valoracion": "med",
    "tend.pro.valoracion": "fav",
    "tend.inm.valoracion": "des",
    "tend.dig.nota": "Podemos automatizar la toma de pedidos y liberar dos personas del mostrador.",
    "tend.gob.nota": "Cada certificación nueva nos cuesta cerca de doce millones y tres meses.",
    "pestel.dg.0": "neu",
    "pestel.dg.1": "neg",
    "pestel.dg.2": "pos",
    "pestel.dg.3": "neu",
    "pestel.dg.4": "pos",
    "pestel.dg.5": "neg",
    "pestel.dg.6": "neu",
    "pestel.dg.7": "neu",
    "pestel.dg.8": "pos",
    "pestel.dg.9": "pos",
    "pestel.sc.0": "pos",
    "pestel.sc.1": "neg",
    "pestel.sc.2": "neu",
    "pestel.sc.3": "neg",
    "pestel.sc.4": "pos",
    "pestel.sc.5": "pos",
    "pestel.sc.6": "neu",
    "pestel.ec.0": "neu",
    "pestel.ec.1": "pos",
    "pestel.ec.2": "neg",
    "pestel.ec.3": "neg",
    "pestel.pl.0": "neg",
    "pestel.pl.1": "neg",
    "pestel.pl.2": "neg",
    "pestel.pl.3": "neu",
    "pestel.pl.4": "neg",
    "pestel.pl.5": "neg",
    "pestel.pl.6": "neu",
    "pestel.pl.7": "neg",
    "pestel.tc.0": "pos",
    "pestel.tc.1": "pos",
    "pestel.tc.2": "neu",
    "pestel.tc.3": "neu",
    "pestel.tc.4": "pos",
    "pestel.tc.5": "pos",
    "pestel.gl.0": "neg",
    "pestel.gl.1": "neu",
    "pestel.gl.2": "pos",
    "pestel.gl.3": "neg",
    "pestel.gl.4": "neu",
    "pestel.gl.5": "neu",
    "pestel.gl.6": "neg",
    "fuerzas.riv.prioridad": "2",
    "fuerzas.riv.impacto": "alto",
    "fuerzas.pro.prioridad": "3",
    "fuerzas.pro.impacto": "medio",
    "fuerzas.com.prioridad": "1",
    "fuerzas.com.impacto": "alto",
    "fuerzas.nue.prioridad": "5",
    "fuerzas.nue.impacto": "medio",
    "fuerzas.sus.prioridad": "4",
    "fuerzas.sus.impacto": "bajo",
    "fuerzas.com.nota": "Tres cadenas concentran el 62% de nuestras ventas y renegocian precio cada semestre.",
    "rasgos.0": "El mercado local de panificación mueve cerca de 180 mil millones al año en el Valle de Aburrá.",
    "rasgos.1": "Cuatro competidores industriales y unas noventa panaderías de barrio.",
    "rasgos.2": "Normatividad sanitaria INVIMA obligatoria y creciente.",
    "rasgos.3": "Tecnificación baja: la mayoría del barrio amasa a mano.",
    "rasgos.4": "El canal institucional crece más rápido que el mostrador.",
    "habitos.0": "Compra diaria, de camino al trabajo, entre 6 y 8 de la mañana.",
    "habitos.1": "Pago en efectivo o transferencia; la tarjeta casi no aparece.",
    "habitos.2": "El pedido institucional se hace por WhatsApp el viernes.",
    "motivadores.0": "Que el pan esté recién salido a la hora que llegan.",
    "motivadores.1": "Cercanía: no caminan más de tres cuadras.",
    "motivadores.2": "Confianza en que el precio no cambia cada mes.",
    "atributos.0": "Frescura del producto en el momento de la compra",
    "atributos.1": "Cumplimiento en la entrega institucional",
    "atributos.2": "Precio estable",
    "atributos.3": "Cercanía del punto",
    "atributos.4": "Variedad de referencias",
    "competidores.competencia-competidores-0.nombre": "Panificadora industrial del sur",
    "competidores.competencia-competidores-0.fortalezas": "Precio bajo, cobertura en toda la ciudad",
    "competidores.competencia-competidores-0.debilidades": "Producto sin frescura, atención impersonal",
    "competidores.competencia-competidores-0.perfil": "Tiendas de barrio y minimercados",
    "competidores.competencia-competidores-0.atributos": "Escala y crédito a 60 días",
    "competidores.competencia-competidores-1.nombre": "Panadería de la esquina",
    "competidores.competencia-competidores-1.fortalezas": "Clientela fiel, pan recién hecho",
    "competidores.competencia-competidores-1.debilidades": "No factura electrónicamente, no entrega a domicilio",
    "competidores.competencia-competidores-1.perfil": "Vecinos del barrio",
    "competidores.competencia-competidores-1.atributos": "Trato personal y horario extendido",
    "competidores.competencia-competidores-2.nombre": "Cadena de café y pan",
    "competidores.competencia-competidores-2.fortalezas": "Marca reconocida, local agradable",
    "competidores.competencia-competidores-2.debilidades": "Precio alto, poca variedad de pan",
    "competidores.competencia-competidores-2.perfil": "Oficinistas de 25 a 40 años",
    "competidores.competencia-competidores-2.atributos": "Experiencia de local y programa de puntos",
    "productivos": [
      "Gestión de clientes",
      "Gestión de la producción",
      "Despacho y ruta",
      "Control de calidad"
    ],
    "soporte": [
      "Financiera y contable"
    ],
    "indicadores.encabezados.a1": "2023",
    "indicadores.encabezados.a2": "2024",
    "indicadores.encabezados.a3": "2025",
    "indicadores.indicadores-indicadores-0.nombre": "Nivel de ventas",
    "indicadores.indicadores-indicadores-0.a1": "1.180.000.000",
    "indicadores.indicadores-indicadores-0.a2": "1.365.000.000",
    "indicadores.indicadores-indicadores-0.a3": "1.520.000.000",
    "indicadores.indicadores-indicadores-1.nombre": "Margen de utilidad total",
    "indicadores.indicadores-indicadores-1.a1": "212.000.000",
    "indicadores.indicadores-indicadores-1.a2": "191.000.000",
    "indicadores.indicadores-indicadores-1.a3": "168.000.000",
    "indicadores.indicadores-indicadores-2.nombre": "Número de clientes",
    "indicadores.indicadores-indicadores-2.a1": "410",
    "indicadores.indicadores-indicadores-2.a2": "455",
    "indicadores.indicadores-indicadores-2.a3": "498",
    "indicadores.indicadores-indicadores-3.nombre": "Gastos totales",
    "indicadores.indicadores-indicadores-3.a1": "968.000.000",
    "indicadores.indicadores-indicadores-3.a2": "1.174.000.000",
    "indicadores.indicadores-indicadores-3.a3": "1.352.000.000",
    "hitos.hitos-hitos-0.anio": "2011",
    "hitos.hitos-hitos-0.hecho": "Abrimos el primer punto con un horno de segunda.",
    "hitos.hitos-hitos-1.anio": "2016",
    "hitos.hitos-hitos-1.hecho": "Entramos al canal institucional con dos colegios.",
    "hitos.hitos-hitos-2.anio": "2020",
    "hitos.hitos-hitos-2.hecho": "La pandemia cerró el mostrador; sobrevivimos por domicilios.",
    "hitos.hitos-hitos-3.anio": "2023",
    "hitos.hitos-hitos-3.hecho": "Compramos la segunda amasadora y duplicamos capacidad.",
    "hitos.hitos-hitos-4.anio": "2025",
    "hitos.hitos-hitos-4.hecho": "Perdimos un contrato institucional grande por precio.",
    "valores.valores-valores-0.valor": "Frescura",
    "valores.valores-valores-0.significado": "Nada sale a la venta con más de seis horas de horneado.",
    "valores.valores-valores-1.valor": "Cumplimiento",
    "valores.valores-valores-1.significado": "Si prometimos las 6 a.m., está a las 6 a.m.",
    "valores.valores-valores-2.valor": "Respeto",
    "valores.valores-valores-2.significado": "Nadie trabaja más de ocho horas sin descanso pago.",
    "valores.valores-valores-3.valor": "Transparencia",
    "valores.valores-valores-3.significado": "El precio se avisa con treinta días de anticipación.",
    "dofa.F.0": "Pan recién hecho a la hora pico",
    "dofa.F.1": "Ruta de domicilios propia",
    "dofa.F.2": "Equipo estable hace años",
    "dofa.D.0": "Dependemos de tres clientes grandes",
    "dofa.D.1": "No tenemos costeo por línea de producto",
    "dofa.O.0": "Canal institucional creciendo",
    "dofa.O.1": "Automatizar la toma de pedidos"
  },
  "filas": [
    {
      "id": "competencia-competidores-0",
      "bloqueId": "competidores",
      "tallerId": "competencia",
      "orden": 0
    },
    {
      "id": "competencia-competidores-1",
      "bloqueId": "competidores",
      "tallerId": "competencia",
      "orden": 1
    },
    {
      "id": "competencia-competidores-2",
      "bloqueId": "competidores",
      "tallerId": "competencia",
      "orden": 2
    },
    {
      "id": "indicadores-indicadores-0",
      "bloqueId": "indicadores",
      "tallerId": "indicadores",
      "orden": 0
    },
    {
      "id": "indicadores-indicadores-1",
      "bloqueId": "indicadores",
      "tallerId": "indicadores",
      "orden": 1
    },
    {
      "id": "indicadores-indicadores-2",
      "bloqueId": "indicadores",
      "tallerId": "indicadores",
      "orden": 2
    },
    {
      "id": "indicadores-indicadores-3",
      "bloqueId": "indicadores",
      "tallerId": "indicadores",
      "orden": 3
    },
    {
      "id": "hitos-hitos-0",
      "bloqueId": "hitos",
      "tallerId": "hitos",
      "orden": 0
    },
    {
      "id": "hitos-hitos-1",
      "bloqueId": "hitos",
      "tallerId": "hitos",
      "orden": 1
    },
    {
      "id": "hitos-hitos-2",
      "bloqueId": "hitos",
      "tallerId": "hitos",
      "orden": 2
    },
    {
      "id": "hitos-hitos-3",
      "bloqueId": "hitos",
      "tallerId": "hitos",
      "orden": 3
    },
    {
      "id": "hitos-hitos-4",
      "bloqueId": "hitos",
      "tallerId": "hitos",
      "orden": 4
    },
    {
      "id": "valores-valores-0",
      "bloqueId": "valores",
      "tallerId": "valores",
      "orden": 0
    },
    {
      "id": "valores-valores-1",
      "bloqueId": "valores",
      "tallerId": "valores",
      "orden": 1
    },
    {
      "id": "valores-valores-2",
      "bloqueId": "valores",
      "tallerId": "valores",
      "orden": 2
    },
    {
      "id": "valores-valores-3",
      "bloqueId": "valores",
      "tallerId": "valores",
      "orden": 3
    }
  ]
};
